import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import { useSession } from "next-auth/react";
import styles from "../../styles/signin.module.css";
import Link from "next/link";

const signin = () => {
  const router = useRouter();
  const { status, data } = useSession();

  const [email, setEmail] = useState("");
  const [foundAlert, setFoundAlert] = useState("");
  const [notFoundAlert, setNotFoundAlert] = useState("");

  const handleSubmit = async (e) => {
    // validate user
    e.preventDefault();

    try {
      const res = await fetch("http://localhost:3000/api/users/check_email", {
        method: "POST",
        body: JSON.stringify({ email }),
        headers: { "Content-Type": "application/json" },
      });

      const user = await res.json();

      if (user.length > 0) {
        setFoundAlert("A link is sent to email. It may take a while.");
        setNotFoundAlert("");
        let fetchedUser = {
          id: user[0].id,
          name: user[0].name,
          email: user[0].email,
          pwd: user[0].pwd,
        };
        console.log(fetchedUser);

        const res2 = await fetch("http://localhost:3000/api/users/reset_pass", {
          method: "POST",
          body: JSON.stringify({ fetchedUser }),
          headers: { "Content-Type": "application/json" },
        });
      } else {
        setFoundAlert("");
        setNotFoundAlert("Email not found.");
        console.log("no user");
      }
    } catch (error) {
      throw error;
    }
  };

  if (status !== "authenticated") {
    return (
      <>
        <Head>
          <title>MotionCPT | Forgot password</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        <main className={styles.signin_div}>
          <form
            className={styles.signin_form}
            action=""
            onSubmit={handleSubmit}
          >
            <h1 className={styles.h1}>Forgot password</h1>
            <input
              className={styles.input_text}
              type="email"
              name="text"
              id=""
              value={email}
              placeholder="Email"
              onChange={(e) => {
                setEmail(e.target.value);
              }}
            />

            <input
              className={styles.signup_btn}
              type="submit"
              value="Continue"
              name="login"
              id=""
            />
            <p className={styles.p_notfound}>{notFoundAlert}</p>
            <p className={styles.p_found}>{foundAlert}</p>

            <p className={styles.p}>
              Don't have an account?{" "}
              <Link className={styles.signup_link} href="/auth/signup">
                Sign up
              </Link>
            </p>
            <p className={styles.p}>
              Already have an accountt?{" "}
              <Link className={styles.signup_link} href="/auth/signin">
                Login
              </Link>
            </p>
          </form>
        </main>
      </>
    );
  } else {
    router.replace("/motion");
  }
  return <div>Loading</div>;
};

export default signin;
